[2/2] Migrate exception assertion to Junit5
google/data-transfer-project pull request #1133
Opened 2022-08-05 17:11 UTC by chaaransen

Migrated from expected exception annotation check (Junit4) to assertThrows method (junit 5)

2022-08-08 10:53 UTC, xokker commented on extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientTest.java
> +    Assertions.assertThrows(IllegalArgumentException.class, () -> {
Could you please use a static import for `assertThrows`? We use static imports for other asserts, so would be nice to keep the code consistent. It applies to every file where we use static imports for assertion functions.

2022-08-08 10:56 UTC, xokker requested changes

2022-08-08 10:56 UTC, xokker commented on extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientTest.java
> +      }
With `assertThrows` we can delete this `try-catch` block and instead verify the monitor call outside the assert block.

2022-08-08 10:56 UTC, xokker commented on extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientTest.java
> +      }
The same here, please remove try-catch

2022-08-08 16:34 UTC, xokker submitted a review, later dismissed

2022-08-10 17:41 UTC, seehamrun approved these changes

2022-08-11 11:16 UTC, xokker approved these changes

2022-08-11 11:24 UTC, merged