check entire Throwable in RetryMapping::matchesThrowable
google/data-transfer-project pull request #1169
Opened 2022-10-04 11:49 UTC by alexeyqu-fb

This becomes important when the original exception (e.g. rate limit exceeded) is shadowed with a wrapping exception somewhere, so the `toString` doesn't contain the important information anymore.

Using `ExceptionUtils.getStackTrace` from `lang3.exception` is one of the ways to look into the stack trace -- however, I am open to suggestions.

cc @xokker

2022-10-04 17:58 UTC, jzacsh commented on portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryMapping.java
>      }
leaving the previous loop seems like a micro-optimization; should we just delete it for now and add something like this (or something else) in later, if we do performance testing and find this area problematic?

2022-10-04 18:01 UTC, jzacsh requested changes
I'm not very familiar with this class, but maybe it'd increase confidence if we started adding unit test coverage? Maybe not to this file, but to its one and only user (as far as I can tell): `RetryStartegyLibrary` itself? eg: maybe then it'd be easy (for future us) to see this PR was just adding a new test case?

2024-06-26 22:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dtinit/data-transfer-project?pullRequest=1169) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dtinit/data-transfer-project?pullRequest=1169) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: alexeyqu-fb<br/>:x: xokker<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dtinit/data-transfer-project?pullRequest=1169) it.</sub>

2026-04-07 15:31 UTC, lisad commented
Closing stale pull request - it's small, so if it's even still needed please re-build

2026-04-07 15:31 UTC, closed without merging