Changes to test jekyll and redirect
google/data-transfer-project pull request #1224
Opened 2023-03-28 20:17 UTC by kateyeo

Changes to check if redirect should be done in markdown or html file and change to check if jekyll is being run.

2023-03-28 20:31 UTC, jzacsh requested changes
any markdown file you touch or produce should be in the root directory. the `_site/` directory is where the static-site generator will put _generated_ files after it consumes what's in the root directory.

2023-03-29 16:47 UTC, jzacsh requested changes

2023-03-29 16:47 UTC, jzacsh commented on _site/documentation.html
> +
lets make one more change to this file just to be *absolutely* sure the change is due to your diret modification and not a redirect_to plugin execution

eg: maybe:
```diff
- Download White Paper
+ Download the White Paper
```

2023-03-29 18:26 UTC, jzacsh approved these changes

2023-03-29 19:34 UTC, kateyeo commented on _site/documentation.html
> +<meta charset="utf-8" />
moved, thanks!

2023-03-29 19:34 UTC, merged