preserves photos filenames when importing
google/data-transfer-project pull request #1227
Opened 2023-04-12 17:33 UTC by aksingh737

2023-04-27 19:46 UTC, jzacsh requested changes
LGTM - just need to sync; eg:

```
# get the latest changes in your repos
git checkout master &&
  git pull upstream master &&
  git push origin master
```

assuming the above went well, then do:

```
# merge the latest changes with your branch
photosImporter=extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
git checkout preserver-filename-photos-fix &&
  git show master:"$photosImporter" > "$photosImporter" &&
  git commit -m 'WIP: reverting fix in prep for file-move from mege' "$photosImporter" &&
  git merge master

# now you can re-write your fix into GPhotosUpload
```

2023-04-27 19:46 UTC, jzacsh commented on extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
> +              photo.getSha1(), photo.getTitle());
note I think this now lives in GPhotosUpload class, so you'll have to revert this file, merge ,and then re-add this param in the new class.

2023-04-27 19:46 UTC, jzacsh commented on extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java
> +    if(!title.isEmpty())
nit: style here is a bit weird - I'm guessing this was just wonkiness from your new IDE setup

2024-06-26 22:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dtinit/data-transfer-project?pullRequest=1227) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dtinit/data-transfer-project?pullRequest=1227) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dtinit/data-transfer-project?pullRequest=1227) it.</sub>

2026-04-07 15:49 UTC, lisad commented
Closing stale pull request - would need to be updated to deal with conflicts

2026-04-07 15:49 UTC, closed without merging