Add support for favorite state metadata for photos and videos models
google/data-transfer-project pull request #1360
Opened 2024-06-05 17:12 UTC by aksingh737

2024-06-07 20:01 UTC, jzacsh requested changes

2024-06-10 18:37 UTC, jzacsh commented on portability-types-common/src/main/java/org/datatransferproject/types/common/models/FavoriteInfo.java
> +    return favorited;
resolved offline; not an issue since jackson will populate this on a java-primitive (not boxed boolean).

2024-06-10 18:49 UTC, jzacsh commented on portability-types-common/src/main/java/org/datatransferproject/types/common/models/FavoriteInfo.java
> +  @JsonProperty("lastUpdateTime")
chatted offline, this happens unfortunately on the VideoModel too, so definitely don't want to block on this right now

but discussed that the way to fix it going forward is to think in terms of `GoogleMediaItem` (proprietary/FP-api objects) as being jackson-constucted and `PhotoModel` (shared object) as being constructed by our own static helpers (eg: `GoogleMediaItem.toVideoModel()` or whatever). tl;dr we'd want to put a new favorited object in the properitiery folder (`google/mediaModels/`) to store the json annotations, and delete them from the shared object.

2024-06-10 19:01 UTC, jzacsh requested changes

2024-06-10 19:01 UTC, jzacsh commented on portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotoModel.java
> +        new FavoriteInfo(false, uploadedTime));
per offline chat: `FavoriteInfo.unfavoritedAt(uploadedTime /*unfavoriteeTime*/)`

2024-06-10 20:30 UTC, aksingh737 commented on portability-types-common/src/main/java/org/datatransferproject/types/common/models/FavoriteInfo.java
> +  public FavoriteInfo(){
Added an unknown method that populated the fields as false for favoritedState and null for updateTime.

2024-06-10 21:10 UTC, jzacsh requested changes

2024-06-10 21:10 UTC, jzacsh commented on portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotoModel.java
> +        FavoriteInfo.unknown());
did you want this one to be `FavoriteInfo.unfavoratedAt(uploadedTime)`?

2024-06-10 21:18 UTC, jzacsh approved these changes

2024-06-10 22:28 UTC, merged